---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-headless
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
